packages:
  - sdk

autoInstallPeers: false
strictPeerDependencies: true

ignoredOptionalDependencies:
  - sharp

overrides:
  postcss: 8.5.22

allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: true
  workerd: true

patchedDependencies:
  vinext: patches/vinext.patch
